ci[gh-action]: fixed download path

diff --git a/.github/workflows/dependency_audit.yml b/.github/workflows/dependency_audit.yml
--- a/.github/workflows/dependency_audit.yml
+++ b/.github/workflows/dependency_audit.yml
@@ -10,36 +10,34 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Check code
+      - name: Checkout code
         uses: actions/checkout@v3
-    
-       # Step to install .NET 9.0 SDK
-      - name: Install .NET 9.0 SDK
-        run: |
-          wget https://download.visualstudio.microsoft.com/download/pr/5d57bc9b-d8d2-49a9-bb29-8fdd63160f7d/d56d7427b7ec15c342fbc2f536ac063f/dotnet-sdk-9.0.100-preview.1.23127.6-linux-x64.tar.gz
-          mkdir -p $HOME/dotnet
-          tar zxf dotnet-sdk-9.0.100-preview.1.23127.6-linux-x64.tar.gz -C $HOME/dotnet
-          echo "$HOME/dotnet" >> $GITHUB_PATH
-         
-        # Run dotnet restore
+
+      # Install .NET 9.0 SDK using setup-dotnet
+      - name: Set up .NET 9.0 SDK
+        uses: actions/setup-dotnet@v3
+        with:
+          dotnet-version: '9.0.x'  # Use a stable or preview version of .NET 9.0
+
+      # Step to restore dependencies
       - name: Restore dependencies
         run: dotnet restore /home/runner/work/Docker-FileOrganize/Docker-FileOrganize/FileOrganizer.csproj
 
-        # Usage of dotnet list package --vulnerable
-      - name: Check dotnet for vulnerable packages.
+      # Step to check dotnet for vulnerable packages
+      - name: Check dotnet for vulnerable packages
         id: check-dependencies
-        run: | 
+        run: |
           dependencies=$(dotnet list package --vulnerable)
           if [[ -n "$dependencies" ]]; then
             echo "Vulnerable packages found."
             echo "$dependencies"
-            echo "vulnerable=true" >> $GITHUB_ENV   # Sets environment variable
+            echo "vulnerable=true" >> $GITHUB_ENV  # Sets environment variable
           else
             echo "No vulnerable packages found."
             echo "vulnerable=false" >> $GITHUB_ENV  # Sets environment variable
           fi
-    
-        # If there are any vulnerable packages present, need to fail. 
-      - name: Fail if there are vulnerable packages.
+
+      # Step to fail the workflow if vulnerable packages are found
+      - name: Fail if there are vulnerable packages
         if: env.vulnerable == 'true'
-        run: exit 1     # Will fail this action.
+        run: exit 1
